### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#10]
The numbers on the left side are not correct. I deleted all downloads and it still has
Compete Downloads 4
Removed Downloads 7

How to reset to 0?

**Comment by DjazzLab** [comment]
Could you try to simply refresh the page ?
Numbers in badges are just the result of a count SQL query. So if numbers are not reset, then downloads status are still in the db.

Could you check the table oc_ocdownloader_queue content ?

**Comment by LIyoai** [comment]
Refresh didn't help.
The table contain old downloads.

**Comment by DjazzLab** [comment]
So the table contains downloads but you don't see anything in the application ?
What's the value in the column STATUS for each line ?

**Comment by LIyoai** [comment]
yes.

STATUS 	
4
4
4
4
4
4
4
5
0
0
5
5

**Comment by DjazzLab** [comment]
STATUS = 5 means download error.
Those downloads don't appear in the application. You simply delete them.

STATUS = 0 means a complete download
STATUS = 4 means a removed download (from aria2, but not completely removed from ocDownloader)

**Comment by LIyoai** [comment]
Should I delete all?

**Comment by DjazzLab** [comment]
When you open the application, one of the first request is "http://.../index.php/apps/ocdownloader/queue/count". The response to this server request is something like "{"ERROR":false,"COUNTER":{"ALL":"2","COMPLETES":"1","ACTIVES":"0","WAITINGS":"0","STOPPED":"0","REMOVED"
:"1"}}"

Could you confirm that the number for each download type can be retrieved in the database by counting queue table lines ?
STATUS = 0 for Completes
STATUS = 1 for Actives
STATUS = 2 for Waitings
STATUS = 3 for Stopped
STATUS = 4 for Removed
STATUS = 5 for Errors

**Comment by LIyoai** [comment]
Not sure if I understand correct.
The numbers and the status on the site and the database are the same.
All Downloads = 9
Complete Downloads = 2
Removed Downloads = 7

Status 0 * 2
Status 4 * 7

4 of the Status 4 have a Is_Cleaned = 1 if this is relevant.

**Comment by DjazzLab** [comment]
So everything is ok.
I mean if you have 7 lines with status 4 in your database, and if you have the number 7 in the removed downloads badge in the application user interface. This is ok.

The is_cleaned flag is just used in the "add downloads" page to allow you to clean actives downloads but without remove them from aria2.
