### ISSUE TITLE
Torrent

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#12]
Sometimes a torrent download is not saved in Downloads but for example in a folder called "Downloadsdebian-update-8.1.9-i386-CD1.iso[1]" in the root directory of the owncloud user.
Also with wrong credentials (root:root) so a normal user can't clean it up.

**Comment by DjazzLab** [comment]
I know this issue, I'll re-check this tonight.

**Comment by DjazzLab** [comment]
This should be fixed in the v1.2
