### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by koylio** [DjazzLab/ocdownloader#13]
Enabling app (current master branch ) causes an iternal server error from owncloud when trying to use the app, or entering OC personal or admin page.

Server: lighttpd-1.4.35
PHP: php-5.6.9
DB: mariadb-10.0.19
OC: owncloud-8.0.4

No errors in other logs. From owncloud.log (username XXXXed):
> {"reqId":"11ec9710339e2b20fff1a4fcda33d835","remoteAddr":"192.168.0.213","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `VAL` FROM `oc_ocdownloader_personalsettings` WHERE `KEY` = ? AND `UID` = ? LIMIT 1' with params [\\\"TorrentsFolder\\\", \\\"XXXX\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_ocdownloader_personalsettings' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `VAL` FR...', Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(54): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/ocdownloader\\\/controller\\\/lib\\\/settings.php(88): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/ocdownloader\\\/controller\\\/indexcontroller.php(48): OCA\\\\ocDownloader\\\\Controller\\\\Lib\\\\Settings->GetValue()\\n#5 [internal function]: OCA\\\\ocDownloader\\\\Controller\\\\IndexController->add()\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\ocDownloader\\\\Controller\\\\IndexController), 'add')\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\ocDownloader\\\\Controller\\\\IndexController), 'add')\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('IndexController', 'add', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(252): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocdownloa...')\\n#13 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":4,"time":"2015-06-12T19:33:02+00:00"}

To me, it looks like the internal server error is caused by missing settings for ocdownloader. I installed it by downloading from github, unpacking to OC apps dir, and enabling app from OC. Maybe I missed a step?

**Comment by DjazzLab** [comment]
Nope, I just have to check sql requests for mariadb. I'll create a VM with your configuration settings.
I think I can publish a fix today...

**Comment by DjazzLab** [comment]
I can't reproduce your internal server :(
I've just installed a virtual machine with your system settings, and everything goes well.

In the apps dir, I've installed ocdownloader with the git clone command. Then I enabled the application in OC. No errors ...

Could you check tables in the database ? Try to remove all ocdownloader tables (3) and remove ocdownloader app folder (after disable it). Then try to reinstall the application.

**Comment by koylio** [comment]
I did check the database. Could this be a namespace collision with old ocdownloader?

App related tables on the database were:
>MariaDB [owncloud]> SELECT * from oc_ocdownloader;
>Empty set (0.00 sec)
>
>MariaDB [owncloud]> SELECT * from oc_ocdownloader_config;
>+---------+--------------+----------+----------+
>| conf_id | conf_version | conf_key | conf_val |
>+---------+--------------+----------+----------+
>|       1 | 2.2          | init     | yes      |
>+---------+--------------+----------+----------+
>1 row in set (0.00 sec)
>
>MariaDB [owncloud]> SELECT * from oc_ocdownloader_providers;
>+-------+------------+---------+
|> pr_id | pr_name    | pr_auth |
>+-------+------------+---------+
>|     1 | HTTP       |       0 |
>|     2 | FTP        |       0 |
>|     3 | RapidShare |       1 |
>|     4 | YouTube    |       0 |
>+-------+------------+---------+
>4 rows in set (0.00 sec)
>
>MariaDB [owncloud]> SELECT * from oc_ocdownloader_users_settings;
>Empty set (0.00 sec)

These look like tables from the old ocdownloader. I tried dropping all the tables and enabling the app again: same error. Any ocdownloader tables weren't created. Then I found this:

>MariaDB [owncloud]> SELECT * from oc_appconfig WHERE appid = "ocdownloader";
>+--------------+-------------------+-------------+
>| appid        | configkey         | configvalue |
>+--------------+-------------------+-------------+
>| ocdownloader | enabled           | yes         |
>| ocdownloader | installed_version | 2.2         |
>| ocdownloader | types             |             |
>+--------------+-------------------+-------------+
>3 rows in set (0.00 sec)

I am thinking that the app framework or something thinks ocdownloader-NG is lower version of the old ocdownloader 2.2 I had tried at some point, and the tables don't get created. I'll investigate some more later, maybe removing the ocdownloader settings from oc_appconfig will sort this out, or just bumping the version at /apps/ocdownloader/appinfo/version.

**Comment by DjazzLab** [comment]
Yes I think you should delete lines from oc_appconfig, and drop new ocDownloader (NG) tables as well.
Then completely remove the ocdownloader app folder.

Finally, download the app again and try to re-enable the app.

**Comment by koylio** [comment]
Just changing the version from oc_appconfig table did the trick.

This gave internal server error:
>MariaDB [owncloud]> SELECT * from oc_appconfig WHERE appid = "ocdownloader";
>+--------------+-------------------+-------------+
>| appid        | configkey         | configvalue |
>+--------------+-------------------+-------------+
>| ocdownloader | enabled           | no          |
>| ocdownloader | installed_version | 2.2         |
>| ocdownloader | types             |             |
>+--------------+-------------------+-------------+
>3 rows in set (0.00 sec)

This made the app work, now the database update process starts after enabling the app, and previously missing tables are created (oc_ocdownloader_adminsettings, oc_ocdownloader_personalsettings, oc_ocdownloader_queue).

>MariaDB [owncloud]> UPDATE oc_appconfig SET configvalue='1.0' WHERE appid='ocdownloader' AND configkey='installed_version';
>Query OK, 1 row affected (0.01 sec)
>Rows matched: 1  Changed: 1  Warnings: 0

>MariaDB [owncloud]> SELECT * from oc_appconfig WHERE appid = >"ocdownloader";+--------------+-------------------+-------------+
>| appid        | configkey         | configvalue |
>+--------------+-------------------+-------------+
>| ocdownloader | enabled           | no          |
>| ocdownloader | installed_version | 1.0         |
>| ocdownloader | types             |             |
>+--------------+-------------------+-------------+
>3 rows in set (0.00 sec)

You should be able to reproduce by removing the ocdownloader_* tables, updating the oc_appconfig tables installed version to higher then current, and enabling ocdownloader from OC.

**Comment by DjazzLab** [comment]
Thanks. I'll write a wiki post for users about this issue ;-)
