### ISSUE TITLE
Returned GID is null ! Is Aria2c running as a daemon ?

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#14]
Updated to 1.2. When I now want to start a download I get
"Returned GID is null ! Is Aria2c running as a daemon?"

ps ax | grep aria
4999 ?        Ss     0:00 aria2c --enable-rpc --rpc-allow-origin-all -c -D --check-certificate=false

**Comment by DjazzLab** [comment]
This error means ocDownloader can't communicate with Aria2 via the json-rpc interface.

Because I change something in the aria2 class in ocDownloader, maybe the json-rpc loopback default address is not use.

I'll check this today

**Comment by ArchGalileu** [comment]
Same problem to me :(

Best regards
ArchGalileu

**Comment by DjazzLab** [comment]
Sorry for the late. I'm currently traveling back home, I think I can fix the bug tonight.

**Comment by DjazzLab** [comment]
The bug will be fixed in the next update (1.2.1)

**Comment by sinus23** [comment]
Returned GID is null ! Is Aria2c running as a daemon ? v1.5

**Comment by ArunJRK** [comment]
Im facing this same issue for https files

**Comment by jajpater** [comment]
Like @ArunJRK I'm also having this problem.

**Comment by blackcrack** [comment]
https://github.com/DjazzLab/ocdownloader/issues/58

@ArunJRK @jajpater
