### ISSUE TITLE
ARAI2 in controller/index.php 

### ISSUE THREAD

**Issue by wealth** [DjazzLab/ocdownloader#15]
totally disables bittorent functionallity on new installs, lel

**Comment by wealth** [comment]
also, line 27 in js/settings/admin.js is not working for me in chrome

**Comment by DjazzLab** [comment]
if you enabled cURL this is normal. if not I don't understand what you mean.

The line 27 in js/settings/admin.js will be fixed in the next update

**Comment by wealth** [comment]
works fine, should i close issue?

**Comment by DjazzLab** [comment]
Nope, I can do it ;-)
