### ISSUE TITLE
Returned GID is null ! Is Aria2c running as a daemon ? on Archlinux

### ISSUE THREAD

**Issue by michaelkuty** [DjazzLab/ocdownloader#18]
I have installed aria2 and started under systemd

● aria2.service - Aria2 User Service by root
   Loaded: loaded (/etc/systemd/system/aria2.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2015-07-04 14:19:55 CEST; 1min 35s ago
 Main PID: 433 (aria2c)
   CGroup: /system.slice/aria2.service
           └─433 /usr/bin/aria2c --enable-rpc --rpc-listen-all --rpc-allow-origin-all --check-certificate=false --save-session /root/.config/aria2/...

Jul 04 14:19:55 box12 systemd[1]: Started Aria2 User Service by root.
Jul 04 14:19:55 box12 systemd[1]: Starting Aria2 User Service by root...
Jul 04 14:19:55 box12 aria2c[433]: 07/04 14:19:55 [NOTICE] IPv4 RPC: listening on TCP port 6800
Jul 04 14:19:56 box12 aria2c[433]: 07/04 14:19:55 [NOTICE] IPv6 RPC: listening on TCP port 6800

but download still says Returned GID is null ! Is Aria2c running as a daemon ?

full excestart ExecStart=/usr/bin/aria2c --enable-rpc --rpc-listen-all --rpc-allow-origin-all --check-certificate=false --save-session %h/.config/aria2/session.lock --input-file %h/.config/aria2/session.lock --conf-path=%h/.config/aria2/aria2.conf

please can you tell me what i do wrong ? i use this tutorial for starting aria2 https://wiki.archlinux.org/index.php/Aria2

Thanks for your time and sorry for my spam(maybe is not really issue)

after some tries i switch dl engine to CURL but Error, GID not found !
version of ocDownloader 1.2.2

**Comment by DjazzLab** [comment]
To be honest, the application has not been tested on ArchLinux.
I'll create a virtual machine with your system configuration to test the application and see what's wrong ...

**Comment by michaelkuty** [comment]
Thanks for your time, please can you tell me if is this configuration is proper ? Must be special user permissions or something else ? Please can you tell me how ocD communicate with ARIA via rest HTTP API and with CURL via CLI ? Where i would search problem ..

**Comment by DjazzLab** [comment]
Yes I think there is a problem with your configuration, but I don't know what yet.
ocDownloader communicate with ARIA2 via a loopback interface (which is not configurable yet) : http://127.0.0.1:6800/jsonrpc

**Comment by michaelkuty** [comment]
yes it's just about my configuratio, sorry for noise !

**Comment by DjazzLab** [comment]
Ok thanks for having noticed me ;-)

**Comment by michaelkuty** [comment]
on arch is systemd and getting aria2 working as daemon was hard to me, but interesting is that not work with CURL.. but i think that is minor issue for 0.1% users :D

**Comment by DjazzLab** [comment]
I think too. But glad to know that ocDownloader works now fine for you ;-)

**Comment by rubinchyk** [comment]
aria2c --enable-rpc --rpc-listen-all
