### ISSUE TITLE
Fallback for ARIA2

### ISSUE THREAD

**Issue by DJaeger** [DjazzLab/ocdownloader#2]
I think it would be great if there would be a fallback for ARIA2 if not available.
The features could be less than with it, but this would allow users of ownCloud in a shared hosting to use at least the core features.

**Comment by DjazzLab** [comment]
Yep I think this would be great. Have the choice to not use ARIA2 to download a file if ARIA2 is not installed on the server.
The very first version of ocdownloader I developed 2 years ago didn't use ARIA2 (https://goo.gl/Kl82Ax) so I think I can implement this ;-)

Thanks for the idea !!

**Comment by DjazzLab** [comment]
This is planned for the v1.2 (or maybe 1.3, I don't know yet)

**Comment by DJaeger** [comment]
Thanks.
This will make this great app usable for much more people.

**Comment by DjazzLab** [comment]
Yep.
Before do that I have to identified each downloads in the download queue by users with their user id (this will be add in the v1.0)

**Comment by DjazzLab** [comment]
The ARIA2 fallback (using CURL) is included in the v1.2.
The downloader should be chosen by the OC Administrator in the Admin panel.
