### ISSUE TITLE
youtubedl on arch linux

### ISSUE THREAD

**Issue by michaelkuty** [DjazzLab/ocdownloader#20]
i'm playing with oc-dl which i've on archlinux and I found that you have absolute path to youtube-dl

 /usr/bin/youtube-dl 'https://youtu.be/lwsIaoCRuOM' --get-url --get-filename -f best
https://r4---sn-2gb7ln76.googlevideo.com/videoplayback?sver=3&expire=1437001780&ms=au&mt=1436980094&mv=m&ipbits=0&mm=31&mn=sn-2gb7ln76&requiressl=yes&ratebypass=yes&source=youtube&pl=19&initcwndbps=2712500&signature=840D2F652AC1F8170FB6E0D00CE8EC2D1CBE1485.DAD3FE706B92C4D4F9364C08D3B51394B5652EA6&fexp=901816%2C9407663%2C9408087%2C9408093%2C9408134%2C9408142%2C9408420%2C9408710%2C9412773%2C9413019%2C9414737%2C9416046%2C9416126%2C9416337%2C9416348%2C9416845&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=1GDVJAOgVz0&mime=video%2Fmp4&id=o-AJifJ0tNh-9jz_TvKnUnm27LEC58O11TTOZiY9QyGETs&itag=22&dur=304.506&lmt=1433847888768458&key=yt5&ip=89.102.34.121
Vladimir 518 - Planeta Praha ft. Martin Svátek & Mike T (OFFICIAL VIDEO)-lwsIaoCRuOM.mp4

on arch is path different with https://wiki.sgc-univ.net/index.php/OCDownloader:Install_The_YouTube-DL_Provider

error from OC Unable to retrieve true YouTube video URL

https://github.com/DjazzLab/ocdownloader/search?utf8=%E2%9C%93&q=%2Fusr%2Flocal%2Fbin%2Fyoutube-dl

/usr/local/bin/youtube-dl

i recommend using `which youtube-dl` before first run or configurable path to CLI or skip them on error

**Comment by DjazzLab** [comment]
Yep I know that I can use which ... but for obscure reasons, using which always falls into error.
So, if you are admin of the ownCloud environment, you can specify the path to youtube-dl in the admin settings.

**Comment by michaelkuty** [comment]
oh my gosh, sorry and thanks :hankey:

**Comment by DjazzLab** [comment]
No problem ;-)
