### ISSUE TITLE
Displayed numbers

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#21]
The displayed numbers for example "All downloads" is not per user.
Downloaded 4 files with my normal account. A '4' is displayed. Login as root or new created test user also a '4' is displayed. 
I don't see the files on the right side, so it's not a privacy issue.

Maybe this is also what caused my issue here https://github.com/DjazzLab/ocdownloader/issues/10

**Comment by LIyoai** [comment]
Already fixed in 1.2.3.
You're fast. You fixed it before I created the issue ;-)

**Comment by DjazzLab** [comment]
I'm flash :-P
