### ISSUE TITLE
Access restriction based on user group

### ISSUE THREAD

**Issue by tigre-bleu** [DjazzLab/ocdownloader#22]
It would be nice to have a setting to limit the access to ocDownloader to specific group(s).

I don't want to give the possility for all my users to download anything from bittorent without control but I would give this permission from trusted users only.

Edit: Sorry, it is already possible from the "Apps" page

**Comment by DjazzLab** [comment]
Yep this is possible from the app page, but you can't allow access to specific protocols for this group or for this other group.
This is a great idea ;-)

For example :
- Group1 : only HTTP downloads allowed
- Group2 : only FTP downloads allowed
- Group3 : only BitTorrent downloads allowed
- Group4 : only YouTube downloads allowed

Then if a user is in Group1 and Group2, he's only allowed to download via HTTP(S) / FTP(S)

This makes sense ;-)

**Comment by DjazzLab** [comment]
I've added some new settings in the future release of ocDownloader (v1.5).
In the admin panel you will be able to allow standard users to use HTTP, FTP, YT or BT protocols.
By default all the protocols are allowed for all.

**Comment by DjazzLab** [comment]
v1.5 released. Issue closed.

**Comment by tigre-bleu** [comment]
The option added is v1.5 is good but imho not enough. It should be possible to select a precise group for each protocol and not only 'admin'.

For instance on my server, I have a group 'collegues', a group 'family' and of course a group 'admin' (with only me in it). I want to allow http, ftp and youtube for everyone but bittorent only to 'family'

**Comment by DjazzLab** [comment]
Ok. I'll work on something to answer your needs.
I'll keep you inform
