### ISSUE TITLE
Use rtorrent to download torrents instead of aria2

### ISSUE THREAD

**Issue by jsalatiel** [DjazzLab/ocdownloader#25]
aria2 torrent is blocked in several private trackers, while rtorrent is still the most well accepted torrent client for linux. Would it be possible to add an option to use rtorrent instead of aria when downloading torrents ?

**Comment by DjazzLab** [comment]
Yes I think this could be possible.
I know that rutorrent uses an xmlrpc interface to rtorrent. I have to check if I can add such a feature to ocDownloader.

**Comment by DjazzLab** [comment]
Hi, uses rtorrent will be available in ocDownloader (NG) v2.0 ;-)

**Comment by jsalatiel** [comment]
When will 2.0 be available ? :)
