### ISSUE TITLE
Disable Bittorrent option

### ISSUE THREAD

**Issue by ezraholm50** [DjazzLab/ocdownloader#28]
Hello,

First of great work the ocdownloader app!!! One question though, is it possible to disable the bittorrent option, since i dont want to download via torrents nor want my users to do so cause of the possible detection and warnings from government/copyright org.

Also, when i'm in the download folder, i cant delete downloaded files, it has to happen from the app. Can this be changed?
great job!

Kind regards,

Ezra

**Comment by DjazzLab** [comment]
Hi !! Thanks ;-)
For now the only way to disable the BitTorrent protocol is to not use ARIA2 but cURL as a download engine. Go to the Admin page, and select the downloader you want to use in ocDownloader Admin settings.

If you want to use ARIA2, but without the BitTorrent protocol possibilities, I should add a new option in a next release !

I'll keep you inform ;-)

**Comment by DjazzLab** [comment]
And for your downloaded files that you can't delete ... several question ;-)
- Do you use the last application version ?
- Do you use the external storage app in ownCloud ?
- Folders are correctly configured in your personnal settings view ?

**Comment by DjazzLab** [comment]
Hi !
Managing permissions for all protocols have been implemented and will be available in the future release v1.5

**Comment by ezraholm50** [comment]
DjazzLab, 

Sorry for the late reply, thank you for everything, i love the app ! Everything works fine now, the issue was i couldnt delete files outside of the ocdownloader app in the download folder. This isnt really required though but I'll look into the settings later on the week, pretty busy right now! Thanks again for all the help and hard work!

Kind regards

**Comment by DjazzLab** [comment]
You're welcome.
Let me know if you need more help.

**Comment by DjazzLab** [comment]
v1.5 released. Issue closed.
