### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by ezraholm50** [DjazzLab/ocdownloader#29]
Hey i'm sorry pretty new to github i wanted to private msg you but dont know how.
Want me to translate ocdownloader in dutch? Its the least i can do for  the help and the great app!

Kind regards,

Ezra

**Comment by DjazzLab** [comment]
Hi Ezra ! Thank you for your message. I think there is no PM feature on GitHub ;-)
But if you want to help me with the dutch language translation, you can go to the [ocDownloader translation project on Transifex](https://www.transifex.com/djazzlab/ocdownloader/). Sign in with your GitHub account and ask to join one of the translation team (or propose your own language).

BTW, I need translators for other projects related to ocDownloader :
- [The Firefox add-on](https://www.transifex.com/djazzlab/ocdownloader-firefox-addon/)
- [The Chrome Extension](https://www.transifex.com/djazzlab/ocdownloader-chrome-extension/)
- The (upcoming) ocDownloader Windows Desktop Client.

Thanks for your help ;-)
