### ISSUE TITLE
Add Torrent Download

### ISSUE THREAD

**Issue by DJaeger** [DjazzLab/ocdownloader#3]
It would be great if it is possible to download by torrent feed or by manually adding an torrent.

I couldn't find (searched only on GH until now) an PHP only solution, but sollutions in PHP to control an local application (like you do it with ARIA2).
As (I think so) torrents are mostly used for big files, it doesn't make much sense to use this feature on a shared hosting solution, so it is not critical to don't offer an PHP only sollution.

I would provide that also as an option, if wanted and supported client is installed.

**Comment by DJaeger** [comment]
But an solution with lesser external dependencies and additional software to be installed, is much easier to install for users, it would be greater to offer a completely integrated solution.
But I'm not sure if it is possible to do it purely in PHP.

**Comment by DjazzLab** [comment]
Hi, sure managing torrents in ocDownloader would be a great feature. And this is already planned for the 1.0 future release (using ARIA2).

The BitTorrent protocol is complicated and I don't think this is possible to develop an only-PHP application to do that.

This is certainly why you don't find anything ;-) But I will check if I can find a working solution on the WEB.

**Comment by efargas** [comment]
http://foro.seguridadwireless.net/openwrt/instalacion-%28facil%29-de-openwrt-en-huawei-553
Here ther are three implementations in php for torrent, rutorrent-webui, transmission-webui and aria webui maybe it can help

**Comment by DjazzLab** [comment]
Yep but all use a backend application (rutorrent, transmission, aria2).
So I'll start with aria2 because this is the first engine used by ocDownloader. Next, maybe I'll be add other backend ...

We'll see ;-)

**Comment by DjazzLab** [comment]
Done
Torrents downloads are now available in the application (using Aria2).

Before downloading you should upload torrent file in torrents folder (default : /Downlaods/Files/Torrents from your user root folder in OC). This setting can be done in the Personal config panel.
