### ISSUE TITLE
curl option has no effect

### ISSUE THREAD

**Issue by llaumgui** [DjazzLab/ocdownloader#33]
Hi,

if I select curl and stop aria2 daemon, I have the message that aria2 daemon not running... I can't use curl.

**Comment by DjazzLab** [comment]
Do you have several screenshots to share with me ? in order to show me what you do to get this error message.
Thanks !

**Comment by llaumgui** [comment]
I select _curl_ in admin interface:
![ocdownload1](https://cloud.githubusercontent.com/assets/411360/9600509/b89554c6-509b-11e5-990a-7b980be370d0.png)

The ocDownloader user interface speak about _aria2_ instead of _curl_, and when I download a file: I have a message that aria2 daemon is missing:
![ocdownload2](https://cloud.githubusercontent.com/assets/411360/9600511/ba39eada-509b-11e5-98af-346bb488ad87.png)

**Comment by DjazzLab** [comment]
Ok so it seems that selecting cURL as download engine is not saved in the database.
When you go back to the admin settings, ARIA2 is still selected right ?

As a temporary solution, you can manually insert a line in the *prefix*_ocdownloader_adminsettings table with :
- KEY = WhichDownloader
- VALUE = CURL

This should resolve your problem for now (but do this only if you know what you are doing !!)

**Comment by llaumgui** [comment]
> When you go back to the admin settings, ARIA2 is still selected right ?

Yes.

**Comment by DjazzLab** [comment]
Ok so running a SQL request like :

`INSERT INTO *prefix*ocdownloader_adminsettings ('KEY', 'VAL') VALUES ('WhichDownloader', 'CURL')` 

should fix your problem.

I'll check this problem in the code soon.

**Comment by llaumgui** [comment]
Hi,

some information:

~~~
sqlite> SELECT * FROM oc_ocdownloader_adminsettings;
1|AllowProtocolBT|N
2|WhichDownloader|CURL
3|WhichDownloader|ARIA2
4|WhichDownloader|CURL
5|WhichDownloader|ARIA2
6|WhichDownloader|CURL
7|AllowProtocolYT|N
8|AllowProtocolYT|Y
9|MaxDownloadSpeed|0
10|YTDLBinary|/usr/sbin/youtube-dl
11|WhichDownloader|ARIA2
12|WhichDownloader|CURL
~~~

**Comment by DjazzLab** [comment]
Hi, you should have only one key "WhichDownloader".
So, delete all the "WhichDownloader" keys except the last one (ID = 12) with a request like :
```DELETE FROM oc_ocdownloader_adminsettings WHERE ID != 12 AND KEY = "WhichDownloader"```
