### ISSUE TITLE
Save path

### ISSUE THREAD

**Issue by christianWilling** [DjazzLab/ocdownloader#35]
I think it will be very useful when i can set another folder as Downloads in settings for maybe an external storage.

it will be much more better if you have placeholder like %user% for the username.

and that the user can set this path by himself.

**Comment by DjazzLab** [comment]
Hi, sorry for the late.
You need such a feature because you want to download a file for another user, right ?
In that case, maybe shared folder can help you to do this right now ;-)

**Comment by christianWilling** [comment]
no i wont to download a file in a remote storage
