### ISSUE TITLE
oc 8.2 not updating file index

### ISSUE THREAD

**Issue by apg1980** [DjazzLab/ocdownloader#40]
hi i have updated my oc from 8.1.3 to 8.2 and infugured out that after download was successfully finished the file Index was not updated so the file was not seen in webfrontend and sync client eather.

my environment ubuntu 14.04 and latest bitnami oc stack.

with 8.1.3 of oc there was no prob. no further log entrys found.

did anybody got this issue too?

**Comment by DjazzLab** [comment]
I'm working on the ocDownloader v2.0 and the compliance with OC 8.2
Do you use the external storage application ? (local, ftp, etc ... drives)

**Comment by apg1980** [comment]
hi no just the onboard storage stuff.

**Comment by DjazzLab** [comment]
Hi, it's a filecache problem within OC.

Several solutions exist to refresh your filescache, check this http://sharadchhetri.com/2013/11/14/how-to-rescan-filesystem-in-owncloud-5

Hope this will help

**Comment by apg1980** [comment]
i know, but thats just a workarround.
thanks for this but why is ocdownloader not updating the filecache?

**Comment by DjazzLab** [comment]
Until now, I'd not the problem but I'll try to add a filecache updater in the next release

**Comment by DjazzLab** [comment]
I've added a trick in the code to refresh the cache. This feature will be available in ocDownloader v2.0
