### ISSUE TITLE
Option for Download / Upload Speed of Bittorrent Protocol

### ISSUE THREAD

**Issue by hitam4450** [DjazzLab/ocdownloader#8]
How about including options for down- / upload speed for Bittorrent protocol ? ( see transmission).

regards, hitam4450

**Comment by DjazzLab** [comment]
I can add a down / up speed limit for each downloads (This could be added in the admin panel for an automatic use) using [max-download-limit](http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--max-download-limit) and [max-upload-limit](http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-u).
But you can use these two options of the aria2c command daemon right now :
- [max-overall-download-limit](http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--max-overall-download-limit)
- [max-overall-upload-limit](http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--max-overall-upload-limit)

**Comment by DjazzLab** [comment]
max-download-limit (all protocols) and max-upload-limit (only bittorrent protocol) options are now implemented in ocDownloader v1.5.
ocDownloader v1.5 will be released by the end of the next week.

**Comment by DjazzLab** [comment]
v1.5 released. Issue closed.
