### ISSUE TITLE
Transform downloads name into a link when the down

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#9]
Link is not correct. I download a file via http and the link of the file is https://.../owncloud/index.php/apps/files?dir=Downloads/Files/Torrents

**Comment by DjazzLab** [comment]
I think this just because one of your setting (DownloadsFolder) has the path "Downloads/Files/Torrents" in your personal settings.

Could you check this ?
What's your ocDownloader version ?

**Comment by LIyoai** [comment]
I have the default folders
/Downloads and /Downloads/Files/Torrents

Version 1.0.2

**Comment by DjazzLab** [comment]
Ok. Thanks for your report, I'll check this tonight in the code.

**Comment by DjazzLab** [comment]
I can't reproduce your issue.
When I add a new download (HTTP or FTP or ...), the link generated when the download is complete redirect me to the folder "Default Downloads Folder" I've set in my personal settings.

**Comment by LIyoai** [comment]
I can't change the folders. It's loading forever when I hit save.
Not sure where it is stored but the database table oc_ocdownloader_personalsettings is empty.

**Comment by DjazzLab** [comment]
Hu very weird !
So the problem is when you hit the Save button for each folder in personal settings.
Do you have any error in a log ?

**Comment by LIyoai** [comment]
I have nothing in my log related to owncloud except a php error every 5minutes regarding my calendar.

**Comment by DjazzLab** [comment]
This is a bug and I just fix it.
The bug happens while the personnalsettings table is empty (like you).

The fix will be delivered in the next release of the application (10.2)
